# This code is licensed under the Custom License.
# For more information, see the LICENSE file in the root directory of this repository.

version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  redis_data:
